### Create Order
POST {{base_url}}/orders
Content-Type: application/json

{
  "ProductId": "P001",
  "Quantity": 1
}

### Cancel Order
DELETE {{base_url}}/orders/67855df7ff5ae14f688ad10f

### Get Order by Id
GET {{base_url}}/orders/67855df7ff5ae14f688ad10f